[workspace]

[package]
name = "coders-yew-example"
version = "0.1.0"
authors = ["Mahmoud Harmouch <oss@wiseai.dev>"]
edition = "2024"

[dependencies]
coders = { path = "../../", features = ["yew"] }
yew = { version = "0.23.0", default-features = false, features = ["csr"] }
yew-router = "0.20.0"
wasm-logger = "0.2.0"
console_error_panic_hook = "0.1.7"

[profile.release]
opt-level = "z"
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"
